<Project>
  <PropertyGroup>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.ApplicationInsights" Version="2.22.0" />
    <PackageReference Update="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Update="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Update="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>
</Project>